
<?php
session_start();

// Check, if username session is NOT set then this page will jump to login page
if (!isset($_SESSION['username'])) {
header('Location: index.html');
}
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "  <title>Bootstrap Example</title>\n";
echo "  <meta charset=\"utf-8\">\n";
echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n";
echo "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n";
echo "  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n";
echo "  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js\"></script>\n";
echo "  <script type=\"text/javascript\">\n";
echo "    $(document).ready(\n";
echo "\n";
echo "\n";
echo "      function()\n";
echo "      {\n";
echo "        \n";
echo "         $.ajax({\n";
echo "        type: \"GET\",\n";
echo "        url: \"retrieve.php\",\n";
echo "        dataType: \"html\",\n";
echo "        success: function(result)\n";
echo "        {\n";
echo "          var names = $(result).find('NAME');\n";
echo "          var cnames=\"\";\n";
echo "\n";
echo "          $(names).each(\n";
echo "            function()\n";
echo "            {\n";
echo "              cnames+= \"<div class='container' id=\"+\"'\"+$(this).text()+\"_'\"+\"><div class='panel panel-default'><div class='panel-body'><b>\"+$(this).text()+\"</b><button id=\"+\"'\"+$(this).text()+\"'\"+\" type='button' style='float: right;' class='btn btn-danger'><b>X</b></button></div></div></div>\";\n";
echo "            }\n";
echo "            );        \n";
echo "          $(\"#panels\").html(cnames);\n";
echo "        }\n";
echo "      });\n";
echo "\n";
echo "     \n";
echo "      $('body').on('click','.btn-danger',function(){\n";
echo "        var name=$(this).attr('id');\n";
echo "        $.ajax({\n";
echo "        type: \"POST\",\n";
echo "        url: \"delete.php\",\n";
echo "        data : {name:name},\n";
echo "        success: function(result)\n";
echo "        {\n";
echo "          $('#'+name+'_').remove();\n";
echo "\n";
echo "        }\n";
echo "        });\n";
echo "        }\n";
echo "        );\n";
echo "\n";
echo " $(\"#add_form\").validate({\n";
echo "\n";
echo "        rules: {\n";
echo "            cname: {\n";
echo "                required: true\n";
echo "            },\n";
echo "            descr: {\n";
echo "                required: true\n";
echo "            },\n";
echo "            formli: {\n";
echo "                required: true\n";
echo "            },\n";
echo "            sheetli: {\n";
echo "                required: true\n";
echo "            }\n";
echo "\n";
echo "        },\n";
echo "        messages: {\n";
echo "            cname: {\n";
echo "                required: \"Please enter company name.\"\n";
echo "            },\n";
echo "            descr: {\n";
echo "                required: \"Please enter Description.\"\n";
echo "            },\n";
echo "            formli: {\n";
echo "                required: \"Please enter link for form.\"\n";
echo "            },\n";
echo "            sheetli: {\n";
echo "                required: \"Please enter link for list.\"\n";
echo "            }\n";
echo "        },\n";
echo "    submitHandler: function(form) {\n";
echo "            var cname=$(\"#cname\").val();\n";
echo "            var descr=$(\"#descr\").val();\n";
echo "            var formli=$(\"#formli\").val();\n";
echo "            var sheetli=$(\"#sheetli\").val();\n";
echo "            var data={cname:cname,descr:descr,formli:formli,sheetli:sheetli}\n";
echo "    \n";
echo "   $.ajax({\n";
echo "    \n";
echo "   type : 'POST',\n";
echo "   url  : 'pushdata.php',\n";
echo "   data : data,\n";
echo "   beforeSend: function()\n";
echo "   { \n";
echo "   \n";
echo "   },\n";
echo "   success :  function(response)\n";
echo "      {      \n";
echo "    location.reload();\n";
echo "     }\n";
echo "   });\n";
echo "    return false;\n";
echo "        }\n";
echo "       });\n";
echo "        \n";
echo "      \n";
echo "\n";

echo "      });\n";
echo "  </script>\n";
echo "  <style>\n";
echo "    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */\n";
echo "    .row.content {height: 1500px}\n";
echo "    \n";
echo "    /* Set gray background color and 100% height */\n";
echo "    .sidenav {\n";
echo "      background-color: #f1f1f1;\n";
echo "      height: 100%;\n";
echo "    }\n";
echo "    \n";
echo "    /* Set black background color, white text and some padding */\n";
echo "    footer {\n";
echo "      background-color: #555;\n";
echo "      color: white;\n";
echo "      padding: 15px;\n";
echo "    }\n";
echo "    \n";
echo "    /* On small screens, set height to 'auto' for sidenav and grid */\n";
echo "    @media screen and (max-width: 767px) {\n";
echo "      .sidenav {\n";
echo "        height: auto;\n";
echo "        padding: 15px;\n";
echo "      }\n";
echo "      .row.content {height: auto;} \n";
echo "    }\n";
echo "  </style>\n";
echo "</head>\n";
echo "<body>\n";
echo "\n";
echo "<div class=\"container-fluid\">\n";
echo "  <div class=\"row content\">\n";
echo "    <div class=\"col-sm-2 sidenav\">\n";
echo "      <h4 style=\"padding-top: 10px\" class=\"text-center\"><b>Welcome, Admin!</b></h4>\n";
echo "      <div style=\"display:table-cell; vertical-align:middle; text-align:center\">\n";
echo "      <img src=\"images/admin.png\" class=\"img-circle\" height=\"100\" width=\"100\" alt=\"Avatar\">\n";
echo "      </div>\n";
echo "      <ul class=\"nav nav-pills nav-stacked\" style=\"padding-top: 10px\">\n";
echo "        <li class=\"active\" data-toggle=\"modal\" data-target=\"#myModal\"><a href=\"#section1\">Add a new company entry</a></li>\n";
echo "        <li class=\"active\"><a href=\"logout.php\">Log Out</a></li>\n";
echo "      </ul><br>\n";
echo "      <!--<div class=\"input-group\">\n";
echo "        <input type=\"text\" class=\"form-control\" placeholder=\"Search Blog..\">\n";
echo "        <span class=\"input-group-btn\">\n";
echo "          <button class=\"btn btn-default\" type=\"button\">\n";
echo "            <span class=\"glyphicon glyphicon-search\"></span>\n";
echo "          </button>\n";
echo "        </span>\n";
echo "      </div>-->\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"col-sm-9\">\n";
echo "\n";
echo "      <br/>\n";
echo "      <h4>RECENT ENTRIES</h4>\n";
echo "      <hr>\n";
echo "\n";
echo "      <div class=\"container\" id=\"panels\">\n";
echo "      </div>\n";
echo "\n";
echo "  <!— Modal —>\n";
echo "  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n";
echo "    <div class=\"modal-dialog\">\n";
echo "    \n";
echo "      <!— Modal content-->\n";
echo "      <div class=\"modal-content\">\n";
echo "        <div class=\"modal-header\">\n";
echo "          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n";
echo "          <h4 class=\"modal-title\">Please enter company details</h4>\n";
echo "        </div>\n";
echo "        <div class=\"modal-body\">\n";
echo "          <form method=\"POST\" id=\"add_form\">\n";
echo "            <div class=\"form-group\">\n";
echo "              <label for=\"cname\">Company name:</label>\n";
echo "            <input type=\"text\" class=\"form-control\" id=\"cname\" name=\"cname\">\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "              <label for=\"descr\">Description:</label>\n";
echo "              <input type=\"text\" class=\"form-control\" id=\"descr\" name=\"descr\">\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "              <label for=\"formli\">Google form link:</label>\n";
echo "              <input type=\"text\" class=\"form-control\" id=\"formli\" name=\"formli\">\n";
echo "            </div>\n";
echo "            <div class=\"form-group\">\n";
echo "              <label for=\"sheetli\">Students sheets link:</label>\n";
echo "              <input type=\"text\" class=\"form-control\" id=\"sheetli\" name=\"sheetli\">\n";
echo "            </div>\n";


echo "            <button type=\"submit\" id=\"add_c\" class=\"btn btn-default\">Submit</button>\n";
echo "          </form>\n";
echo "        </div>\n";
echo "        <div class=\"modal-footer\">\n";
echo "          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n";
echo "        </div>\n";
echo "      </div>  \n";
echo "    </div>\n";
echo "  </div>\n";
echo "<!---->\n";
echo "\n";
echo "\n";
echo "    </div>\n";
echo "  </div>\n";
echo "</div>\n";
echo "\n";
echo "<footer class=\"container-fluid\">\n";
echo "  <p>Footer Text</p>\n";
echo "</footer>\n";
echo "\n";
echo "</body>\n";
echo "</html>";

?>